### ISSUE TITLE
Update mp-itdvp to work with higher-order Hamiltonians

### ISSUE THREAD

**Issue by jesse-osborne** [mptoolkit/mptoolkit#11]
At the moment, `mp-itdvp` is designed to work with first-order Hamiltonians. After performing a sweep, the program updates the E/F-matrices for the unit cell boundary by subtracting off the energy from the last/right component respectively, but this will not work if the Hamiltonian is higher order.

The proper solution would be to run the MPO solver after each sweep, but this may be expensive, so I may do it only if the Hamiltonian is higher-order (or add a command line option). This would probably be much faster if I use the previous E/F-matrices as an initial guess.

@ianmccul, if I set the first argument of `SolveHamiltonianMPO_Left`/`Right` to the previous E/F-matrices, will it use the previous values as initial guesses for the solvers?

**Comment by ianmccul** [comment]
I don't think it will use the initial guess, but that can be added I think.  I'm not sure how useful it will be though because the parts where it needs to run the linear solver are exactly the ones that have higher order parts that will add stuff to the E-matrices.  I guess they should always be in the direction of the identity though, so we can orthogonalize the initial vectors furst.

But I think you probably can just recycle the E/F matrices - that is exactly what iDMRG does.  Do you know why that doesn't work for tdvp?

**Comment by jesse-osborne** [comment]
If you start with the unit cell in right-canonical form, with the E matrix on the left, and then perform a sweep across the unit cell, the E matrix that you will get at the other end will be $E(1)$, while the initial one will be $E(0)$, where $E(n)$ is the polynomial form of the E matrix.

For a first-order Hamiltonian, the difference between $E(1)$ and $E(0)$ is component in the direction of the identity proportional to the energy density in the last element, so you can just subtract it off.

This is what is done in `mp-idmrg-s3e` and `mp-itdvp`:
https://github.com/ianmccul/mptoolkit-dev/blob/f85cc4cd7e351440e3a8db6030ca7c2642690093/mp/mp-idmrg-s3e.cpp#L678
https://github.com/ianmccul/mptoolkit-dev/blob/f790cd6297566744de9892b86c264c33cbabc2c1/mp-algorithms/itdvp.cpp#L175

But presumably this doens't work properly if the Hamiltonian is not first-order?

**Comment by ianmccul** [comment]
It works OK.  The higher order parts of the MPO mean that other terms in the E matrices have growing components, but this is harmless.  well, eventually I guess they will overflow, but not for a while.

**Comment by jesse-osborne** [comment]
Then I guess it may already be able to work.

At the moment, the MPO solver is run after each timestep only for time-dependent Hamiltonians (since the form of the MPO is not guaranteed to be the same each timestep).
https://github.com/ianmccul/mptoolkit-dev/blob/f790cd6297566744de9892b86c264c33cbabc2c1/mp-algorithms/itdvp.cpp#L771-L775
I guess we could just modify this to resolve the MPO each timestep for higher-order Hamiltonians if it does start to overflow.
