### ISSUE TITLE
Questions about the new infinitewavefunctionright.h

### ISSUE THREAD

**Issue by jesse-osborne** [mptoolkit/mptoolkit#31]
@ianmccul

https://github.com/ianmccul/mptoolkit-dev/blob/cb604df4e804eb6570b68c4d86c7830f191d57f1/wavefunction/infinitewavefunctionright.h#L74
I don't think this method is used anywhere. Should it be removed?

https://github.com/ianmccul/mptoolkit-dev/blob/cb604df4e804eb6570b68c4d86c7830f191d57f1/wavefunction/infinitewavefunctionright.h#L117-L118
Shouldn't it be possible to have a version of `get_left_canonical` which doesn't change the unit cell boundary, and would only need to return two objects, like `get_right_canonical` for `InfiniteWavefunctionLeft`? I guess you could just do an explicit conversion to `InfiniteWavefunctionLeft` and then use `get_left_canonical`, but it doesn't seem very consistent.

**Comment by ianmccul** [comment]
Yes to both of these, I intended to make `get_left_canonical` do that, but it looks like I overlooked it.
The quick hack implementation would be
```
std::pair<LinearWavefunction, RealDiagonalOperator>
get_left_canonical(InfiniteWavefunctionRight const& Psi)
{
   return get_left_canonical(InfiniteWavefunctionLeft(Psi));
}
```
I'll look at doing the proper version later tonight.
