### ISSUE TITLE
Finding Hamiltonian fixed points with nontrivial qshift

### ISSUE THREAD

**Issue by jesse-osborne** [mptoolkit/mptoolkit#9]
`mp-idmrg-s3e` and `mp-itdvp` crash when trying to calculate the Hamiltonian fixed point when there is a nontrivial qshift in the unit cell.

We can initialise a wavefunction with
```
$ bosehubbard-u1 -o lattice -N 5
$ mp-idmrg-s3e -H "lattice:H_J+4*H_U" -w psi.t0.0 -m 50x100 -q 2 -bf
```
Then trying to restart `mp-idmrg-s3e` or run `mp-itdvp` fails
```
$ mp-idmrg-s3e -H "lattice:H_J+4*H_U" -w psi.t0.0 -m 50x100
$ mp-itdvp -H "lattice:H_J+2*H_U" -w psi.t0.0 -t 0.1 -n 100 -o psi
```
There is probably a missing `delta_shift` somewhere in either `mp-idmrg-s3e` and `mp-itdvp` or in the MPO sovler itself.

These commands work properly on the old version of the code.

**Comment by ianmccul** [comment]
yes quite likely, I didn't test it on anything that has a non-zero qshift.  it is certainly in the MPO solver.

**Comment by jesse-osborne** [comment]
It just looks like the basis checks at the start of `SolveSimpleMPO_Right` were using `Psi.Basis1()` instead of `Psi.Basis2()`. It seems to work properly now.
